/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf9fa",
        "primary-container": "#f06292",
        "primary-fixed": "#ffd9e1",
        "on-tertiary-container": "#471f30",
        "on-error": "#ffffff",
        "secondary-container": "#a2c5fe",
        "on-secondary-fixed-variant": "#214779",
        "tertiary-container": "#bb8498",
        "surface-container": "#eeedee",
        "secondary-fixed-dim": "#a7c8ff",
        "inverse-primary": "#ffb1c5",
        "on-primary-fixed-variant": "#8b0e45",
        "surface-container-low": "#f4f3f4",
        "secondary-fixed": "#d5e3ff",
        "on-secondary-fixed": "#001c3b",
        "on-secondary-container": "#2c5183",
        "tertiary-fixed": "#ffd9e4",
        "on-surface": "#1a1c1d",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f1f0f1",
        "tertiary-fixed-dim": "#f2b6cb",
        "surface-variant": "#e3e2e3",
        "tertiary": "#805062",
        "on-primary-fixed": "#3f001b",
        "primary": "#ab2c5d",
        "surface-container-highest": "#e3e2e3",
        "surface-tint": "#ab2c5d",
        "inverse-surface": "#2f3032",
        "outline-variant": "#ddbfc5",
        "on-tertiary-fixed": "#330f1f",
        "error-container": "#ffdad6",
        "on-primary-container": "#5e002b",
        "on-tertiary": "#ffffff",
        "secondary": "#3b5f92",
        "outline": "#8a7176",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e9",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb1c5",
        "on-surface-variant": "#574146",
        "surface-bright": "#faf9fa",
        "on-tertiary-fixed-variant": "#65394b",
        "on-background": "#1a1c1d",
        "background": "#faf9fa",
        "surface-dim": "#dadadb"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}
